# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Features
      labels:
        - 'feature'
    - title: Internal
      labels:
        - 'internal'
    - title: Other Changes
      labels:
        "*"
