# Source: https://github.com/render-examples/fastapi/blob/main/render.yaml
services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: python3 -m pip install .
    startCommand: uvicorn my_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8001
