
name: Build and push python image to GCP Artifact Registry

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-gcr:
    name: Build and Push to GCP Artifact Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test-name-of-thing
      PROJECT_ID: clean-framework-410217
      REPOSITORY_ID: test-simple-api
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: GCP Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: GCP SDK Setup
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ PROJECT_ID }}
    
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .
    
    - name: COnfigure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
    
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$IMAGE_NAME:$GIT_TAG
        docker push us-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$IMAGE_NAME:latest
        docker push us-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_ID/$IMAGE_NAME:$GIT_TAG
